version: '3.7'

services:

  sql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql
    hostname: sql
    networks:
      sb:
        ipv4_address: 172.18.0.4
    volumes:
      - ./data:/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
  
  pg-db:
   image: postgres:latest
   restart: always
   container_name: pg
   hostname: pg
   networks:
      sb:
        ipv4_address: 172.18.0.3 
   volumes:
    - ./data:/data    
   environment:
    POSTGRES_PASSWORD: P@ssw0rd

  spark:
    image: asami76/spark-hadoop:latest
    container_name: sparkc
    hostname: sparkc
    networks:
      sb:
        ipv4_address: 172.18.0.2
    volumes:
      - ./data:/data
    tty: true
    stdin_open: true
networks:
  sb:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/24
