version: '3.7'

services:

  sql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql
    hostname: sql
    volumes:
      - ./data:/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
  
  pg-db:
   image: postgres:latest
   restart: always
   container_name: pg
   hostname: pg 
   volumes:
    - ./data:/data    
   environment:
    POSTGRES_PASSWORD: P@ssw0rd

  spark:
    image: asami76/spark-hadoop:latest
    container_name: sparkc
    hostname: sparkc
    volumes:
      - ./data:/data
    tty: true
    stdin_open: true